// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nido.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nido.Infrastructure.Migrations
{
    [DbContext(typeof(NidoDbContext))]
    [Migration("20260527225314_SeedHogarElectrodomesticos")]
    partial class SeedHogarElectrodomesticos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.AsignacionesTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarea_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("asignaciones_tarea_pkey");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("asignaciones_tarea", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.CategoriasProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<int?>("TtlDias")
                        .HasColumnType("integer")
                        .HasColumnName("ttl_dias");

                    b.HasKey("Id")
                        .HasName("categorias_producto_pkey");

                    b.ToTable("categorias_producto", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Electrodomestico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("electrodomesticos_pkey");

                    b.HasIndex("HogarId");

                    b.ToTable("electrodomesticos", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("PagadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("pagado_por");

                    b.HasKey("Id")
                        .HasName("gastos_pkey");

                    b.HasIndex("PagadoPor");

                    b.HasIndex(new[] { "HogarId" }, "idx_gastos_hogar");

                    b.ToTable("gastos", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Hogare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("hogares_pkey");

                    b.ToTable("hogares", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.InfoNutricionalProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("Calorias")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("calorias");

                    b.Property<decimal?>("Carbohidratos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carbohidratos");

                    b.Property<decimal?>("Grasas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("grasas");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<decimal?>("Proteinas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("proteinas");

                    b.HasKey("Id")
                        .HasName("info_nutricional_producto_pkey");

                    b.HasIndex("ProductoId");

                    b.ToTable("info_nutricional_producto", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.InfoNutricionalRecetum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("Calorias")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("calorias");

                    b.Property<decimal?>("Carbohidratos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carbohidratos");

                    b.Property<decimal?>("Grasas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("grasas");

                    b.Property<decimal?>("Proteinas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("proteinas");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.HasKey("Id")
                        .HasName("info_nutricional_receta_pkey");

                    b.HasIndex("RecetaId");

                    b.ToTable("info_nutricional_receta", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.IngredientesRecetum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_ingrediente");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<string>("Unidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unidad");

                    b.HasKey("Id")
                        .HasName("ingredientes_receta_pkey");

                    b.HasIndex("ProductoId");

                    b.HasIndex(new[] { "RecetaId" }, "idx_ingredientes_receta");

                    b.ToTable("ingredientes_receta", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.InvitacionesHogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Codigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("ExpiraEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<Guid>("InvitadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("invitado_por");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("invitaciones_hogar_pkey");

                    b.HasIndex("HogarId");

                    b.HasIndex("InvitadoPor");

                    b.ToTable("invitaciones_hogar", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.ListaCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("AgregadoAlInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("agregado_al_inventario");

                    b.Property<Guid>("AgregadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("agregado_por");

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad");

                    b.Property<bool?>("Comprado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("comprado");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("Unidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unidad");

                    b.HasKey("Id")
                        .HasName("lista_compras_pkey");

                    b.HasIndex("AgregadoPor");

                    b.HasIndex("ProductoId");

                    b.HasIndex(new[] { "HogarId" }, "idx_lista_compras_hogar");

                    b.ToTable("lista_compras", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Logro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("IconoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icono_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("logros_pkey");

                    b.ToTable("logros", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.LogrosHogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<Guid>("LogroId")
                        .HasColumnType("uuid")
                        .HasColumnName("logro_id");

                    b.HasKey("Id")
                        .HasName("logros_hogar_pkey");

                    b.HasIndex("HogarId");

                    b.HasIndex("LogroId");

                    b.ToTable("logros_hogar", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.LogrosUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("FechaObtenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_obtenido")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LogroId")
                        .HasColumnType("uuid")
                        .HasColumnName("logro_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("logros_usuario_pkey");

                    b.HasIndex("LogroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logros_usuario", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.MiembrosHogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<int?>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("puntos");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("miembros_hogar_pkey");

                    b.HasIndex(new[] { "HogarId" }, "idx_miembros_hogar_hogar");

                    b.HasIndex(new[] { "UsuarioId" }, "idx_miembros_hogar_usuario");

                    b.ToTable("miembros_hogar", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Notificacione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_tipo");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("notificaciones_pkey");

                    b.HasIndex(new[] { "UsuarioId" }, "idx_notificaciones_usuario");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("productos_pkey");

                    b.HasIndex("CategoriaId");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Dificultad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dificultad");

                    b.Property<string>("FuenteId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fuente_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Porciones")
                        .HasColumnType("integer")
                        .HasColumnName("porciones");

                    b.Property<int?>("TiempoCoccionMin")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_coccion_min");

                    b.HasKey("Id")
                        .HasName("recetas_pkey");

                    b.ToTable("recetas", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.RecetaElectrodomestico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<string>("TipoRequerido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_requerido");

                    b.HasKey("Id")
                        .HasName("receta_electrodomestico_pkey");

                    b.HasIndex("RecetaId");

                    b.ToTable("receta_electrodomestico", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.RecetasCocinada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CocinadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("cocinado_por");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<int?>("PorcionesCocinadas")
                        .HasColumnType("integer")
                        .HasColumnName("porciones_cocinadas");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.HasKey("Id")
                        .HasName("recetas_cocinadas_pkey");

                    b.HasIndex("CocinadoPor");

                    b.HasIndex("HogarId");

                    b.HasIndex("RecetaId");

                    b.ToTable("recetas_cocinadas", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.ReseniasRecetum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Puntuacion")
                        .HasColumnType("integer")
                        .HasColumnName("puntuacion");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("resenias_receta_pkey");

                    b.HasIndex("RecetaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("resenias_receta", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.RestriccionesUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("restricciones_usuario_pkey");

                    b.HasIndex("UsuarioId");

                    b.ToTable("restricciones_usuario", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.StockHogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("CantidadActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad_actual");

                    b.Property<Guid>("CargadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("cargado_por");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EstaAbierto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("esta_abierto");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<decimal>("PorcentajeConsumido")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("porcentaje_consumido");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Alacena")
                        .HasColumnName("ubicacion");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unidad_medida");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("stock_hogar_pkey");

                    b.HasIndex("CargadoPor");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "HogarId" }, "idx_stock_hogar_hogar");

                    b.ToTable("stock_hogar", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CompletadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("completado_por");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_completado");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_limite");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uuid")
                        .HasColumnName("hogar_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("tareas_pkey");

                    b.HasIndex("CompletadoPor");

                    b.HasIndex("CreadoPor");

                    b.HasIndex(new[] { "HogarId" }, "idx_tareas_hogar");

                    b.ToTable("tareas", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("OauthId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("oauth_id");

                    b.Property<string>("OauthProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oauth_provider");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("usuarios_pkey");

                    b.HasIndex(new[] { "Email" }, "usuarios_email_key")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.AsignacionesTarea", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Tarea", "Tarea")
                        .WithMany("AsignacionesTareas")
                        .HasForeignKey("TareaId")
                        .IsRequired()
                        .HasConstraintName("asignaciones_tarea_tarea_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "Usuario")
                        .WithMany("AsignacionesTareas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("asignaciones_tarea_usuario_id_fkey");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Electrodomestico", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("Electrodomesticos")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("electrodomesticos_hogar_id_fkey");

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Gasto", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("Gastos")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("gastos_hogar_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "PagadoPorNavigation")
                        .WithMany("Gastos")
                        .HasForeignKey("PagadoPor")
                        .IsRequired()
                        .HasConstraintName("gastos_pagado_por_fkey");

                    b.Navigation("Hogar");

                    b.Navigation("PagadoPorNavigation");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.InfoNutricionalProducto", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Producto", "Producto")
                        .WithMany("InfoNutricionalProductos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("info_nutricional_producto_producto_id_fkey");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.InfoNutricionalRecetum", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Receta", "Receta")
                        .WithMany("InfoNutricionalReceta")
                        .HasForeignKey("RecetaId")
                        .IsRequired()
                        .HasConstraintName("info_nutricional_receta_receta_id_fkey");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.IngredientesRecetum", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Producto", "Producto")
                        .WithMany("IngredientesReceta")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("ingredientes_receta_producto_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Receta", "Receta")
                        .WithMany("IngredientesReceta")
                        .HasForeignKey("RecetaId")
                        .IsRequired()
                        .HasConstraintName("ingredientes_receta_receta_id_fkey");

                    b.Navigation("Producto");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.InvitacionesHogar", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("InvitacionesHogars")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("invitaciones_hogar_hogar_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "InvitadoPorNavigation")
                        .WithMany("InvitacionesHogars")
                        .HasForeignKey("InvitadoPor")
                        .IsRequired()
                        .HasConstraintName("invitaciones_hogar_invitado_por_fkey");

                    b.Navigation("Hogar");

                    b.Navigation("InvitadoPorNavigation");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.ListaCompra", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "AgregadoPorNavigation")
                        .WithMany("ListaCompras")
                        .HasForeignKey("AgregadoPor")
                        .IsRequired()
                        .HasConstraintName("lista_compras_agregado_por_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("ListaCompras")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("lista_compras_hogar_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Producto", "Producto")
                        .WithMany("ListaCompras")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("lista_compras_producto_id_fkey");

                    b.Navigation("AgregadoPorNavigation");

                    b.Navigation("Hogar");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.LogrosHogar", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("LogrosHogars")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("logros_hogar_hogar_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Logro", "Logro")
                        .WithMany("LogrosHogars")
                        .HasForeignKey("LogroId")
                        .IsRequired()
                        .HasConstraintName("logros_hogar_logro_id_fkey");

                    b.Navigation("Hogar");

                    b.Navigation("Logro");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.LogrosUsuario", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Logro", "Logro")
                        .WithMany("LogrosUsuarios")
                        .HasForeignKey("LogroId")
                        .IsRequired()
                        .HasConstraintName("logros_usuario_logro_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "Usuario")
                        .WithMany("LogrosUsuarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("logros_usuario_usuario_id_fkey");

                    b.Navigation("Logro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.MiembrosHogar", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("MiembrosHogars")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("miembros_hogar_hogar_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "Usuario")
                        .WithMany("MiembrosHogars")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("miembros_hogar_usuario_id_fkey");

                    b.Navigation("Hogar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Notificacione", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("notificaciones_usuario_id_fkey");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Producto", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.CategoriasProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("productos_categoria_id_fkey");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.RecetaElectrodomestico", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Receta", "Receta")
                        .WithMany("RecetaElectrodomesticos")
                        .HasForeignKey("RecetaId")
                        .IsRequired()
                        .HasConstraintName("receta_electrodomestico_receta_id_fkey");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.RecetasCocinada", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "CocinadoPorNavigation")
                        .WithMany("RecetasCocinada")
                        .HasForeignKey("CocinadoPor")
                        .IsRequired()
                        .HasConstraintName("recetas_cocinadas_cocinado_por_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("RecetasCocinada")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("recetas_cocinadas_hogar_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Receta", "Receta")
                        .WithMany("RecetasCocinada")
                        .HasForeignKey("RecetaId")
                        .IsRequired()
                        .HasConstraintName("recetas_cocinadas_receta_id_fkey");

                    b.Navigation("CocinadoPorNavigation");

                    b.Navigation("Hogar");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.ReseniasRecetum", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Receta", "Receta")
                        .WithMany("ReseniasReceta")
                        .HasForeignKey("RecetaId")
                        .IsRequired()
                        .HasConstraintName("resenias_receta_receta_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "Usuario")
                        .WithMany("ReseniasReceta")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("resenias_receta_usuario_id_fkey");

                    b.Navigation("Receta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.RestriccionesUsuario", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "Usuario")
                        .WithMany("RestriccionesUsuarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("restricciones_usuario_usuario_id_fkey");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.StockHogar", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "CargadoPorNavigation")
                        .WithMany("StockHogarCargadoPorNavigations")
                        .HasForeignKey("CargadoPor")
                        .IsRequired()
                        .HasConstraintName("stock_hogar_cargado_por_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("StockHogars")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("stock_hogar_hogar_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Producto", "Producto")
                        .WithMany("StockHogars")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("stock_hogar_producto_id_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "UpdatedByNavigation")
                        .WithMany("StockHogarUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .IsRequired()
                        .HasConstraintName("stock_hogar_updated_by_fkey");

                    b.Navigation("CargadoPorNavigation");

                    b.Navigation("Hogar");

                    b.Navigation("Producto");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Tarea", b =>
                {
                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "CompletadoPorNavigation")
                        .WithMany("TareaCompletadoPorNavigations")
                        .HasForeignKey("CompletadoPor")
                        .IsRequired()
                        .HasConstraintName("tareas_completado_por_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Usuario", "CreadoPorNavigation")
                        .WithMany("TareaCreadoPorNavigations")
                        .HasForeignKey("CreadoPor")
                        .IsRequired()
                        .HasConstraintName("tareas_creado_por_fkey");

                    b.HasOne("Nido.Infrastructure.Persistence.Entities.Hogare", "Hogar")
                        .WithMany("Tareas")
                        .HasForeignKey("HogarId")
                        .IsRequired()
                        .HasConstraintName("tareas_hogar_id_fkey");

                    b.Navigation("CompletadoPorNavigation");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.CategoriasProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Hogare", b =>
                {
                    b.Navigation("Electrodomesticos");

                    b.Navigation("Gastos");

                    b.Navigation("InvitacionesHogars");

                    b.Navigation("ListaCompras");

                    b.Navigation("LogrosHogars");

                    b.Navigation("MiembrosHogars");

                    b.Navigation("RecetasCocinada");

                    b.Navigation("StockHogars");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Logro", b =>
                {
                    b.Navigation("LogrosHogars");

                    b.Navigation("LogrosUsuarios");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Producto", b =>
                {
                    b.Navigation("InfoNutricionalProductos");

                    b.Navigation("IngredientesReceta");

                    b.Navigation("ListaCompras");

                    b.Navigation("StockHogars");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Receta", b =>
                {
                    b.Navigation("InfoNutricionalReceta");

                    b.Navigation("IngredientesReceta");

                    b.Navigation("RecetaElectrodomesticos");

                    b.Navigation("RecetasCocinada");

                    b.Navigation("ReseniasReceta");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Tarea", b =>
                {
                    b.Navigation("AsignacionesTareas");
                });

            modelBuilder.Entity("Nido.Infrastructure.Persistence.Entities.Usuario", b =>
                {
                    b.Navigation("AsignacionesTareas");

                    b.Navigation("Gastos");

                    b.Navigation("InvitacionesHogars");

                    b.Navigation("ListaCompras");

                    b.Navigation("LogrosUsuarios");

                    b.Navigation("MiembrosHogars");

                    b.Navigation("Notificaciones");

                    b.Navigation("RecetasCocinada");

                    b.Navigation("ReseniasReceta");

                    b.Navigation("RestriccionesUsuarios");

                    b.Navigation("StockHogarCargadoPorNavigations");

                    b.Navigation("StockHogarUpdatedByNavigations");

                    b.Navigation("TareaCompletadoPorNavigations");

                    b.Navigation("TareaCreadoPorNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
