// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nido.Infrastructure.Persistence;

#nullable disable

namespace Nido.Infrastructure.Migrations
{
    partial class NidoDbContextModelSnapshot
    {
        internal void BuildModelForMigration(ModelBuilder modelBuilder)
            => BuildModel(modelBuilder);
    }

    [DbContext(typeof(NidoDbContext))]
    [Migration("20260702160000_AddTemaPreferidoToUsuarios")]
    partial class AddTemaPreferidoToUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new NidoDbContextModelSnapshot().BuildModelForMigration(modelBuilder);
        }
    }
}
